[package]
name = "ch1"
version = "0.1.0"
authors = ["Joseph Dane <joe.dane@gmail.com>"]
edition = "2018"

[dependencies]

ndarray = "0.13.0"
ndarray-linalg = { version = "0.12.0", features = ["openblas"] }